                <div id="nmu_search_block">
                        <h3>Search | News Monitoring</h3>

                        <form class="search-form" id="nmu-search-form" action="/content/nmu-search">

                                <div class="input-group">
                                        <input type="text" class="form-control" id="searchQuery" name="query">
                                        <span class="input-group-btn">
                                                <button class="btn btn-primary" type="submit" id="searchTrigger" value="Go">Search</button>
                                        </span>
                                </div>

                                <div class="row">
                                        <div class="col-md-6">
                                                <div class="muted date-label">From date</div>
                                        </div>
                                        <div class="col-md-6">
                                                <div class="muted date-label">To date</div>
                                        </div>
                                </div>

                                <div class="row">
                                        <div class="col-md-6">
                                                <div class="input-group date">
                                                        <input type="text" class="form-control" name="searchDateInputFrom" id="searchDateInputFrom">
                                                        <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
                                                </div>
                                        </div>
                                        <div class="col-md-6">
                                                <div class="input-group date">
                                                        <input type="text" class="form-control" name="searchDateInputTo" id="searchDateInputTo">
                                                        <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
                                                </div>
                                        </div>
                                </div>

                        </form>


                </div>